apiVersion: v1
kind: ConfigMap
metadata:
    name: nginx-conf
data:
    nginx.conf: |

        server {
            listen 80;
            index index.php index.html;
            root /usr/share/nginx/html;

            # rewrite ^/google$ http://google.com permanent;
        }
    entrypoint.sh: |
        #!/bin/bash
        echo 'Code.education Rocks' > /usr/share/nginx/html/index.html 