apiVersion: apps/v1
selector:
    matchLabels:
        app: hello-nginx
kind: Deployment
metadata: 
    name: hello-nginx
spec:
    template:
        metadata:
            labels:
                app: hello-nginx
        spec:
            containers:
            - name: nginx
              image: nginx:1.17-alpine
              ports:
              - containerPort: 80